import braintree
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from orders.models import Order

#instantiate Braintree payment gateway
gateway= braintree.BraintreeGateway(settings.BRAINTREE_CONF) #Create a braintree instance

def payment_process(request):
    order_id= request.session.get('order_id') #get the order stored in the session create in order_create
    order = get_object_or_404(Order,id=order_id) #retreive the order object
    total_cost= order.get_total_cost()

    if request.method== "POST":
        #retreive nonce
        nonce= request.POST.get('payment_method_nonce',None)
        #Create and Submit transaction
        result = gateway.transaction.sale({
            'amount': f'{total_cost:.2f}', #two decimal places
            'payment_method_nonce': nonce, #the token nonce generated by braintree for the payment
            'options': {
                'submit_for_settlement':True #submit the transaction for settlement automatically
            }
        })
        if result.is_success:
            #mark order as paid
            order.paid = True
            #store the unique transaction ID
            order.braintree_id = result.transaction.id
            order.save()
            return redirect('payment:done')
        else:
            return redirect('payment:canceled')

    else:
        #generate token
        client_token= gateway.client_token.generate()
        return render(request, 'payment/process.html', {'order': order, 'client_token': client_token})


def payment_done(request):
    return render(request,'payment/done.html')


def payment_canceled(request):
    return render(request,'payment/canceled.html')

