# Generated by Django 3.2.6 on 2021-08-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='location.continent'),
            preserve_default=False,
        ),
    ]
