# Generated by Django 3.2.6 on 2021-08-08 11:42

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_country_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='continent', chained_model_field='continent', null=True, on_delete=django.db.models.deletion.CASCADE, to='location.country'),
        ),
    ]
