# Generated by Django 4.0 on 2021-12-18 12:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_feed_time', models.DateTimeField(default=datetime.datetime(2021, 12, 18, 12, 50, 20, 495152, tzinfo=utc))),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.species')),
            ],
        ),
    ]
