# Generated by Django 4.0 on 2021-12-18 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='last_feed_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 13, 7, 28, 498535, tzinfo=utc)),
        ),
    ]
