# Generated by Django 3.2.7 on 2021-10-18 22:41

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_picture',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/home/joviski/PycharmProjects/drf_tutorial/media')),
        ),
    ]
