# Generated by Django 3.2.7 on 2021-10-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_account_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_picture',
            field=models.ImageField(blank=True, null=True, upload_to='drf_tutorial/media'),
        ),
    ]
