# Generated by Django 3.2.4 on 2021-06-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
